// WHAT THIS PRODUCT CAN BIND TOGETHER.
//
// @xeplr/actions ships the actions; this file decides which of them THIS app
// offers, and registers them once at startup (see bin/www). Whatever a workflow
// step turns out to be, it will name one of these — so the registry is
// populated before the first request rather than lazily.
//
// A deliberate WHITELIST rather than "register everything the package exports",
// for two reasons. Some built-ins are more dangerous than others —
// spawnProgram runs arbitrary executables — and offering one should be a
// decision somebody made, visible in a diff, not a side effect of upgrading a
// dependency. And several entries in that package are PLACEHOLDERS: modules
// with a comment saying the implementation is pending and nothing else in them.
// Registering one would put a name in the catalog, draw it in the step picker,
// and fail at the moment somebody relied on it.
//
// So the list below is names this app WANTS, and readiness is checked against
// the package rather than assumed. A name that is not ready yet stays in the
// list, out of the catalog, and lands the day the package implements it.
var actions = require('@xeplr/actions');
var xcfgSetup = require('../db/xcfgSetup');

// The keys on @xeplr/actions' `builtins`, not the action names — those are
// kebab-case and assigned by the modules themselves (`dbFetch` registers as
// `db-fetch`). Naming the export is what makes this list checkable.
var WANTED = [
  'dbFetch',
  'dbPush',
  'dbQuery',
  // Calling a procedure is its own step now — it used to be reachable only by
  // running a movement, which meant a procedure that returns nothing could not
  // be run at all.
  'dbProcedure',
  'dbListTables',
  'dbListViews',
  'dbListProcedures',
  'dbListColumns',
  'fileMove',

  // Email. The five inbound ones are what a workflow monitors a mailbox with;
  // emailSend is also what a `wait` step uses to deliver its own resume link
  // (see workflowRunner's mintResumeKey — the key is available to the step's
  // own action as {resumeKey}).
  //
  // emailDelete is offered but worth knowing about: it is a permanent expunge,
  // not a move to Trash. emailMove to a trash folder is the reversible one.
  'emailRead',
  'emailMove',
  'emailDelete',
  'emailDownloadEmail',
  'emailDownloadAttachments',
  'sendEmail'
];

// THIS APP'S OWN ACTIONS — not from @xeplr/actions, and not placeholders.
//
// Glue between two products, which is exactly why it is not in the shared
// action library: @xeplr/actions must not learn what a job is. Registered the
// same way and appearing in the same catalog, so the step editor needs no
// notion that some actions come from here and some from there.
var LOCAL = [
  require('./actions/jobRun')
];

// REGISTERED BUT NOT OFFERED.
//
// An action a step can legitimately name, that no author should ever pick off
// a palette. The registry must have it — the engine resolves a step's
// actionName through the registry, so a step naming an unregistered action
// cannot run at all — but catalog() leaves it out, because the only thing that
// knows how to build one of these steps is the facade that owns them.
//
// `screen-show` is the case: a screens flow's steps are generated by
// lib/flows.js from a design held in another app, and one dropped by hand onto
// the ordinary workflow canvas would park its run forever — nothing outside
// that facade knows how to show the screen or how to resume it. Hiding it is
// not secrecy; it is not offering half of something.
var HIDDEN = [
  require('./actions/screenShow')
];

var HIDDEN_NAMES = HIDDEN.map(function(def) { return def.name; });

// Needs the control-plane connection to record what moved where, so it is
// registered separately once xcfgSetup has resolved.
var WANTED_WITH_META = ['fileUpload'];

// DELIBERATELY ABSENT: spawnProgram. It runs arbitrary executables, which is a
// different kind of permission from "call an HTTP endpoint" — named here so
// that leaving it out reads as a decision rather than an oversight.

/** A module the registry will actually accept, as opposed to a placeholder. */
function isReady(def) {
  return Boolean(def && typeof def.execute === 'function' && def.name);
}

function offer(key, def, registered, skipped) {
  if (!isReady(def)) { skipped.push(key); return; }
  actions.register(def);
  registered.push(def.name);
}

/**
 * Registers this app's actions and returns their names.
 *
 * Idempotent — @xeplr/actions' register() overwrites by name, so calling this
 * twice leaves the registry in the same state rather than doubling it.
 */
function registerAll() {
  var registered = [];
  var skipped = [];

  WANTED.forEach(function(key) {
    offer(key, actions.builtins[key], registered, skipped);
  });

  LOCAL.forEach(function(def) {
    offer(def.name, def, registered, skipped);
  });

  // Same registration, no catalog entry — see HIDDEN.
  HIDDEN.forEach(function(def) {
    offer(def.name, def, registered, skipped);
  });

  WANTED_WITH_META.forEach(function(key) {
    var entry = actions.builtins[key];
    // Factory-shaped in some versions, a plain module in others. Both are
    // handled rather than asserted, because which one it is is the package's
    // business and not worth breaking a boot over.
    //
    // Guarded because reading xcfgSetup.metaStore THROWS when the
    // control-plane connection was never established — which is a real state
    // for an embedded host (see registerWorkflow, where xeplr_configs is
    // best-effort). Losing one action to that is correct; losing the whole
    // catalog, and with it every other action, is not.
    try {
      var def = typeof entry === 'function' ? entry({ metaKnex: xcfgSetup.metaStore }) : entry;
      offer(key, def, registered, skipped);
    } catch (err) {
      console.warn('[actions] ' + key + ' could not be registered: ' + err.message);
      skipped.push(key);
    }
  });

  // Said out loud, once, at startup. A name silently missing from the picker is
  // a bug somebody spends an afternoon on; a line in the boot log is not.
  if (skipped.length) {
    console.warn('[actions] not yet implemented in @xeplr/actions, so not offered: ' + skipped.join(', '));
  }

  return registered;
}

/**
 * The catalog, as the UI needs it: name, description and the INPUT SCHEMA that
 * describes what each one takes.
 *
 * The schema is the point. A step editor told separately what an action accepts
 * is a second description of it, and the day the two disagree the form collects
 * a field the action ignores. Sending the registry's own schema means the form
 * is generated from the thing it is a form for.
 *
 * The EXECUTOR is not sent, and could not usefully be — it is a function, it
 * would not survive JSON, and an endpoint that hands out executors is an
 * endpoint that explains how to bypass itself.
 */
function catalog() {
  return actions.list().filter(function(a) {
    // HIDDEN is registered, so the engine can run a step that names it, and
    // absent here, so no palette ever draws it. Filtered at the point the list
    // leaves the process rather than by not registering it — the two questions
    // ("can this run" and "should anyone pick it") have different answers.
    return HIDDEN_NAMES.indexOf(a.name) === -1;
  }).map(function(a) {
    return {
      name: a.name,
      description: a.description,
      inputSchema: a.inputSchema,
      outputSchema: a.outputSchema
    };
  });
}

module.exports = {
  registerAll: registerAll,
  catalog: catalog,
  isReady: isReady,
  WANTED: WANTED,
  WANTED_WITH_META: WANTED_WITH_META,
  LOCAL: LOCAL,
  HIDDEN: HIDDEN
};
