// The claims stepSources.js makes about turning a palette item into a step.
// Every one of these is a thing that would look correct on the canvas and
// fail at run time.
import assert from 'node:assert/strict'
import {
  jobStepKey, jobToStep, actionToStep, sourceFor, isReadOnly,
  JOB_STEP_ACTION, JOBS_URL_BINDING, RESUME_URL_BINDING
} from '../src/stepSources.js'

let checks = 0
function check(label, fn) { fn(); checks++; console.log('  ok  ' + label) }

console.log('jobStepKey')
check('reads as a name, not an id', () => {
  assert.equal(jobStepKey({ id: 'x7f3k', name: 'Load Sales' }, []), 'load_sales')
})
check('punctuation and spacing collapse', () => {
  assert.equal(jobStepKey({ name: '  Nightly — ERP → BI!! ' }, []), 'nightly_erp_bi')
})
check('the same job twice gets distinct keys', () => {
  const first = jobStepKey({ name: 'Load Sales' }, [])
  const second = jobStepKey({ name: 'Load Sales' }, [first])
  assert.equal(first, 'load_sales')
  assert.equal(second, 'load_sales_2')
  assert.notEqual(first, second)   // else the two overwrite each other in the run context
})
check('a nameless job still gets a usable key', () => {
  assert.equal(jobStepKey({}, []), 'job')
})
check('an unprintable name does not produce an empty key', () => {
  assert.equal(jobStepKey({ name: '!!!' }, []), 'job')
})

console.log('\njobToStep')
const step = jobToStep({ id: 'j1', name: 'Load Sales' }, 3, [])
check('waits — the chain must not walk on while the job runs', () => {
  assert.equal(step.kind, 'wait')
})
check('stops on failure', () => {
  assert.equal(step.onError, 'stop')
})
check('names the job-run action', () => {
  assert.equal(step.actionName, JOB_STEP_ACTION)
})
check('carries the job id', () => {
  assert.equal(step.values.jobId, 'j1')
})
check('binds the callback — a step without it can never be resumed', () => {
  assert.equal(step.values.callbackUrl, RESUME_URL_BINDING)
})
check('binds the jobs URL from server env, never a browser-known host', () => {
  assert.equal(step.values.jobsUrl, JOBS_URL_BINDING)
  assert.ok(!/^https?:/.test(step.values.jobsUrl))
})
check('keeps its position', () => {
  assert.equal(step.position, 3)
})

console.log('\nactionToStep — unchanged behaviour')
const a = actionToStep({ name: 'db-move' }, 0)
check('auto, not wait', () => { assert.equal(a.kind, 'auto') })
check('blank key for the author to fill', () => { assert.equal(a.stepKey, '') })

console.log('\nsourceFor')
check('no kind → the action canvas', () => {
  assert.equal(sourceFor({}).kind, 'workflow')
  assert.equal(sourceFor(null).kind, 'workflow')
})
check('kind jobs → the job palette', () => {
  assert.equal(sourceFor({ kind: 'jobs' }).kind, 'jobs')
  assert.equal(sourceFor({ kind: 'jobs' }).pickFirst, true)
})
check('an unknown kind falls back rather than breaking the editor', () => {
  assert.equal(sourceFor({ kind: 'martians' }).kind, 'workflow')
})


console.log('\nautoNameFromSteps — a name nobody was asked for')
{
  const { autoNameFromSteps, SOURCES } = await import('../src/stepSources.js')
  check('the steps are the description', () => {
    assert.equal(
      autoNameFromSteps([{ name: 'Load Sales' }, { name: 'Refresh Cube' }]),
      'Load Sales → Refresh Cube'
    )
  })
  check('a long chain keeps both ends — the last step identifies it too', () => {
    assert.equal(
      autoNameFromSteps([{ name: 'A' }, { name: 'B' }, { name: 'C' }, { name: 'D' }]),
      'A → … → D'
    )
  })
  check('deleted steps are not part of the name', () => {
    assert.equal(
      autoNameFromSteps([{ name: 'A' }, { name: 'B', deleted: true }, { name: 'C' }]),
      'A → C'
    )
  })
  check('falls back to the step key when unnamed', () => {
    assert.equal(autoNameFromSteps([{ stepKey: 'load_sales' }]), 'load_sales')
  })
  check('nothing to derive from returns null, not "→"', () => {
    assert.equal(autoNameFromSteps([]), null)
    assert.equal(autoNameFromSteps(null), null)
    assert.equal(autoNameFromSteps([{ deleted: true, name: 'A' }]), null)
  })
  check('a workflow still requires its own name', () => {
    assert.equal(SOURCES.workflow.autoName, null)
    assert.equal(typeof SOURCES.jobs.autoName, 'function')
  })
  check('each source speaks its own language', () => {
    assert.equal(SOURCES.jobs.backTo, 'jobs')
    assert.equal(SOURCES.workflow.backTo, 'workflows')
    assert.notEqual(SOURCES.jobs.emptyCanvas, SOURCES.workflow.emptyCanvas)
    assert.ok(!/workflow/i.test(SOURCES.jobs.emptyCanvas), 'the jobs canvas never says "workflow"')
    assert.ok(!/workflow/i.test(SOURCES.jobs.namePlaceholder))
  })

  // ── a flow of screens is DRAWN here and EDITED elsewhere ────────────────
  //
  // Its steps are generated by the backend from a design held in another app
  // (@xeplr/workflow's lib/flows.js), and the backend's own workflow save route refuses
  // one outright. The canvas draws it so a run can be followed; it edits
  // nothing, and the reason it edits nothing is this flag rather than a branch
  // on `kind` inside a component.
  check('a screens workflow is read-only', () => {
    assert.equal(isReadOnly({ kind: 'screens' }), true)
  })
  check('...and the other two are not', () => {
    assert.equal(isReadOnly({ kind: 'workflow' }), false)
    assert.equal(isReadOnly({ kind: 'jobs' }), false)
  })
  check('an unsaved workflow with no kind yet is editable', () => {
    assert.equal(isReadOnly(null), false)
    assert.equal(isReadOnly({}), false)
  })
  check('every source answers the question, so no call site needs a default', () => {
    Object.keys(SOURCES).forEach((k) => assert.equal(typeof SOURCES[k].readOnly, 'boolean'))
  })
  check('it carries the sentence saying where it IS editable', () => {
    // The same words the backend refuses a save with — somebody who hits both
    // should read one answer, not two.
    assert.equal(SOURCES.screens.readOnlyNotice, 'This flow is designed in Configure UI')
  })
  check('sourceFor finds it by kind', () => {
    assert.equal(sourceFor({ kind: 'screens' }).kind, 'screens')
  })
  check('adding a step here throws rather than making one the server will discard', () => {
    assert.throws(() => SOURCES.screens.toStep({ id: 's1' }, 0, []))
  })
  check('a flow never has to be named here', () => {
    assert.equal(SOURCES.screens.autoName, null)
    assert.ok(!/workflow/i.test(SOURCES.screens.emptyCanvas), 'a flow canvas never says "workflow"')
  })
}

console.log('\n' + checks + ' checks passed')
